"""AgentSession

Revision ID: 4fa61bf17137
Revises: c9b34c8a56b9
Create Date: 2026-02-12 10:06:20.395136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa61bf17137'
down_revision: Union[str, Sequence[str], None] = 'c9b34c8a56b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('id_sessao', sa.String(), nullable=False),
    sa.Column('id_agente', sa.String(), nullable=True),
    sa.Column('token_sessao', sa.String(), nullable=True),
    sa.Column('ip_origem', sa.String(), nullable=True),
    sa.Column('user_agent_dispositivo', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_agente'], ['agent.id_agente'], ),
    sa.PrimaryKeyConstraint('id_sessao')
    )
    op.create_index(op.f('ix_agent_sessions_token_sessao'), 'agent_sessions', ['token_sessao'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_sessions_token_sessao'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
