"""add_system_tables

Revision ID: c9b34c8a56b9
Revises: 
Create Date: 2026-02-11 08:26:03.940509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b34c8a56b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id_agente', sa.String(), nullable=False),
    sa.Column('nome_agente', sa.String(), nullable=True),
    sa.Column('ip_local', sa.String(), nullable=True),
    sa.Column('id_hardware', sa.String(), nullable=True),
    sa.Column('status_atual', sa.String(), nullable=True),
    sa.Column('ultima_conexao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_agente'),
    sa.UniqueConstraint('id_hardware')
    )
    op.create_table('globalconfig',
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('user',
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('permissoes', sa.String(length=2), nullable=True),
    sa.Column('digital_cadastrada', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('agentconfig',
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.Column('id_agente', sa.String(), nullable=True),
    sa.Column('chave', sa.String(), nullable=True),
    sa.Column('valor', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_agente'], ['agent.id_agente'], ),
    sa.PrimaryKeyConstraint('id_config')
    )
    op.create_table('biometria',
    sa.Column('id_biometria', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.String(), nullable=True),
    sa.Column('hash_biometrico', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_biometria')
    )
    op.create_table('command',
    sa.Column('id_comando', sa.Integer(), nullable=False),
    sa.Column('id_agente', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_agente'], ['agent.id_agente'], ),
    sa.PrimaryKeyConstraint('id_comando')
    )
    op.create_table('log',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_agente', sa.String(), nullable=True),
    sa.Column('evento', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_agente'], ['agent.id_agente'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_table('notification',
    sa.Column('id_notificacao', sa.Integer(), nullable=False),
    sa.Column('id_agente', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_agente'], ['agent.id_agente'], ),
    sa.PrimaryKeyConstraint('id_notificacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('log')
    op.drop_table('command')
    op.drop_table('biometria')
    op.drop_table('agentconfig')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('globalconfig')
    op.drop_table('agent')
    # ### end Alembic commands ###
